[server]
# Configurazioni per Streamlit Cloud
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false

[browser]
# Configurazioni browser
gatherUsageStats = false

[theme]
# Tema personalizzato
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
# Configurazioni client
showErrorDetails = true
